### ISSUE TITLE
raw_page=page.get() returns now None

### ISSUE THREAD

**Issue by AlexMikhalev** [ArnaudValensi/ArnaudValensi.github.io#3]
Hello Arnaud, 
I tried to follow you example, but failed with error
```
None
Traceback (most recent call last):
  File "./bin/get-blog-posts.py", line 147, in <module>
    to_markdown(root_page_id, ignore=ignore_root)
  File "./bin/get-blog-posts.py", line 121, in to_markdown
    if 'format' in raw_page and 'page_cover' in raw_page['format']:
TypeError: argument of type 'NoneType' is not iterable

```
Seems like get() now returns None, Python 3.8.5, notion.__version__
Out[2]: '0.0.6'
from pip.

**Comment by AlexMikhalev** [comment]
Propose quickfix:
```
    metas.append(f"title: '{page_title}'")

    if hasattr(page,'cover') and page.cover:
        page_cover_url = 'https://www.notion.so/' + page.cover
        cover_image_name = download_file(page_cover_url, dest_path)
        metas.append(f"featured: '{cover_image_name}'")
```

**Comment by chaos2171053** [comment]
> Propose quickfix:
> 
> ```
>     metas.append(f"title: '{page_title}'")
> 
>     if hasattr(page,'cover') and page.cover:
>         page_cover_url = 'https://www.notion.so/' + page.cover
>         cover_image_name = download_file(page_cover_url, dest_path)
>         metas.append(f"featured: '{cover_image_name}'")
> ```

Thanks for quickfix. 
No "/" in "www.notion.so/"
