### ISSUE TITLE
Error `requests.exceptions.HTTPError: Invalid input.`

### ISSUE THREAD

**Issue by AnzenKodo** [ArnaudValensi/ArnaudValensi.github.io#7]
This my [Repo](https://github.com/FillyAgioro/fillyagioro.github.io)
My Notion [File](https://www.notion.so/Blog-Post-2cc01b6d5f1e4153b472dbf464b926b9)
My [Run](https://github.com/FillyAgioro/fillyagioro.github.io/runs/2428497127?check_suite_focus=true):

```bash
Run pipenv install
Creating a virtualenv for this project…
Pipfile: /home/runner/work/fillyagioro.github.io/fillyagioro.github.io/Pipfile
Using /opt/hostedtoolcache/Python/3.8.9/x64/bin/python3.8 (3.8.9) to create virtualenv…
created virtual environment CPython3.8.9.final.0-64 in 360ms
  creator CPython3Posix(dest=/home/runner/.local/share/virtualenvs/fillyagioro.github.io-S0ycJAFM, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/runner/.local/share/virtualenv)
    added seed packages: pip==21.0.1, setuptools==56.0.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator


Successfully created virtual environment!
Virtualenv location: /home/runner/.local/share/virtualenvs/fillyagioro.github.io-S0ycJAFM
Pipfile.lock (e734c5) out of date, updating to (f33982)…
Locking [dev-packages] dependencies…
Locking [packages] dependencies…

Building requirements...

Resolving dependencies...

Success!
Updated Pipfile.lock (f33982)!
Installing dependencies from Pipfile.lock (f33982)…
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
-> Cleaning the "content/blog" folder
Traceback (most recent call last):
  File "./bin/get-blog-posts.py", line 146, in <module>
    to_markdown(root_page_id, ignore=ignore_root)
  File "./bin/get-blog-posts.py", line 109, in to_markdown
    page = client.get_block(page_id)
  File "/home/runner/.local/share/virtualenvs/fillyagioro.github.io-S0ycJAFM/lib/python3.8/site-packages/notion/client.py", line 118, in get_block
    block = self.get_record_data("block", block_id, force_refresh=force_refresh)
  File "/home/runner/.local/share/virtualenvs/fillyagioro.github.io-S0ycJAFM/lib/python3.8/site-packages/notion/client.py", line 111, in get_record_data
    return self._store.get(table, id, force_refresh=force_refresh)
  File "/home/runner/.local/share/virtualenvs/fillyagioro.github.io-S0ycJAFM/lib/python3.8/site-packages/notion/store.py", line 184, in get
    self.call_load_page_chunk(id)
  File "/home/runner/.local/share/virtualenvs/fillyagioro.github.io-S0ycJAFM/lib/python3.8/site-packages/notion/store.py", line 286, in call_load_page_chunk
    recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
  File "/home/runner/.local/share/virtualenvs/fillyagioro.github.io-S0ycJAFM/lib/python3.8/site-packages/notion/client.py", line 209, in post
    raise HTTPError(
requests.exceptions.HTTPError: Invalid input.
Error: Process completed with exit code 1.
```

**Comment by Indosaram** [comment]
`notion-py` has changed some api due to authenticaion chage. You can refer [my repo](https://github.com/Indosaram/notion2gatsby) which forked this repository.
